# Generated by Django 4.1.7 on 2023-04-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occa_name', models.CharField(max_length=255)),
                ('occ_spec', models.CharField(max_length=255)),
                ('occ_image', models.ImageField(upload_to='occations')),
                ('occ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.occations'),
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
