# Generated by Django 4.1.7 on 2023-04-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_occations_alter_booking_doc_name_delete_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='c_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='c_phone',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='occa_name',
        ),
    ]
